version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: com.github.ben-manes.caffeine:caffeine
        versions:
          - "> 2.8.8"
      - dependency-name: com.github.TownyAdvanced:Towny
        versions:
          - "> 0.96.2.0"
      - dependency-name: io.sentry:sentry
        versions:
          - "> 3.1.1"
      - dependency-name: net.kyori:adventure-text-serializer-gson
        versions:
          - "> 4.2.0, < 5"
      - dependency-name: net.minidev:json-smart
        versions:
          - "> 1.3.2"
      - dependency-name: net.tnemc:Reserve
        versions:
          - "> 0.1.3.0"
      - dependency-name: org.junit.jupiter:junit-jupiter
        versions:
          - "> RELEASE"
      - dependency-name: org.slf4j:slf4j-nop
        versions:
          - "> 1.7.6"
      - dependency-name: com.massivecraft:Factions
        versions:
          - 1.6.9.5-2.6.8-STABLE
      - dependency-name: com.github.angeschossen:LandsAPI
        versions:
          - 5.2.1
          - 5.2.2
          - 5.3.2
          - 5.3.3
          - 5.5.5
